language: cpp
dist: trusty

cache:
    apt: true


os:
    - linux
    - osx

addons:
    apt:
        sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - cmake-data
            - gcc-6
            - gfortran-6

compiler:
    - clang
    - gcc

before_script:
    - pip install meson
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
    - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp -O include/catch.hpp

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest

notifications:
  email: false
