language: cpp

cache: pip

python: 3.5

os: linux

compiler:
    - clang

before_script:
    - pip3 install meson
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
    - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp -O include/catch.hpp

script:
    - mkdir build && cd build
    - meson ..
    - ninja test

notifications:
  email: false
