language: python

cache: pip apt

addons:
    apt:
        sources:
            - 'kalakris-cmake'
        packages:
            - ninja-build

python:
    - "3.5"

os: linux

compiler:
    - clang

before_script:
    - pip install meson
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
    - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp -O include/catch.hpp

script:
    - mkdir build && cd build
    - meson.py ..
    - ninja test

notifications:
  email: false
