language: cpp
dist: trusty

cache:
    apt: true


os:
    - linux
    - osx

osx_image: xcode7.3

addons:
    apt:
        sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - cmake-data
            - gcc-6
            - gfortran-6
            - g++-6

compiler:
    - gcc

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
    - wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp -O include/catch.hpp
    - export FC=gfortran-6
    - export CC=gcc-6
    - export CXX=g++-6

script:
    - mkdir build && cd build
    - cmake .. -D WITH_SBF_TESTS=YES
    - make
    - ctest -C WITH_SBF_TESTS

notifications:
  email: false
